BEGIN;
CREATE TABLE schema_migration(version integer PRIMARY KEY, applied_at timestamptz DEFAULT now());
CREATE TABLE app_user(id text PRIMARY KEY, profile jsonb NOT NULL);
CREATE TABLE app_snapshot(id integer PRIMARY KEY CHECK(id=1),data jsonb NOT NULL);
CREATE TABLE meeting(id text PRIMARY KEY,user_id text NOT NULL REFERENCES app_user(id),title text NOT NULL,platform text NOT NULL,data jsonb NOT NULL);
CREATE TABLE meeting_participant(id text PRIMARY KEY,meeting_id text NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,data jsonb NOT NULL);
CREATE TABLE transcript_segment(id text PRIMARY KEY,meeting_id text NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,data jsonb NOT NULL);
CREATE TABLE meeting_event(id text PRIMARY KEY,meeting_id text NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,data jsonb NOT NULL);
CREATE TABLE attention_event(id text PRIMARY KEY,meeting_id text NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,score integer NOT NULL CHECK(score BETWEEN 0 AND 100),status text NOT NULL CHECK(status IN ('DETECTED','NOTIFIED','SEEN','ACKNOWLEDGED','RESPONDED','DISMISSED','EXPIRED')),data jsonb NOT NULL);
CREATE INDEX attention_meeting ON attention_event(meeting_id,status);
CREATE INDEX transcript_meeting ON transcript_segment(meeting_id);
CREATE TABLE task(id text PRIMARY KEY,meeting_id text NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,data jsonb NOT NULL);
CREATE TABLE decision(id text PRIMARY KEY,meeting_id text NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,data jsonb NOT NULL);
CREATE TABLE meeting_summary(id text PRIMARY KEY,meeting_id text NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,data jsonb NOT NULL);
CREATE TABLE ai_analysis(id text PRIMARY KEY,meeting_id text NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,data jsonb NOT NULL);
CREATE TABLE ai_usage(id text PRIMARY KEY,meeting_id text NOT NULL REFERENCES meeting(id) ON DELETE CASCADE,provider text NOT NULL,model text NOT NULL,tokens integer NOT NULL,latency_ms integer NOT NULL,estimated_cost numeric NOT NULL DEFAULT 0);
CREATE TABLE attention_event_feedback(id text PRIMARY KEY,event_id text NOT NULL REFERENCES attention_event(id) ON DELETE CASCADE,rating text NOT NULL,reason text NOT NULL DEFAULT '');
INSERT INTO schema_migration(version) VALUES(1);
COMMIT;
